### ISSUE TITLE
Svg Not getting Created

### ISSUE THREAD

**Issue by alison84r** [bjhamltn/CGM-SVG.NET#1]
Hi, 
I was trying to create the Svg from the code. But There is a problem i am facing. Loop is running indefinitely. 

            getNextMetaElement(ref br, ref buffer, out bytesread, ref paramLen, out elemclass, out elemId, out elemName, Cgm_Elements);

            while (bytesread > 0)
            {
                if (!string.IsNullOrEmpty(elemName))
                //if (elemName != "")
                {
                    parseMetaElement(ref br, ref buffer, ref bytesread, ref paramLen, ref elemclass, ref elemId, ref elemName, ref Cgm_Elements, true);
                }
                else
                {
                    getNextMetaElement(ref br, ref buffer, out bytesread, ref paramLen, out elemclass, out elemId, out elemName, Cgm_Elements);
                }
            }           
            br.Close();

            CGM_t_SVG(Cgm_Elements);

**Comment by bjhamltn** [comment]
Can you send me a copy of the CGM that you are trying to convert?  
bjhamltn@gmail.com

**Comment by bjhamltn** [comment]
I was able to decode and convert the CGM files that you sent.  

Could you try to comment out the JCGM code that is used for testing. The JCGM does not fully support your CGM file.

```
        #region JCGM CGM used for testing and tunning
            //java.io.File cgmFile = new java.io.File(cgmfilename_in);
            //java.io.DataInputStream input = new java.io.
            //DataInputStream(new java.io.FileInputStream(cgmFile));
            //net.sf.jcgm.core.CGM cgm = new CGM();
            //cgm.read(input);
            //List<Command> commands = cgm.getCommands().toArray().
           //Cast<Command>().ToList();
            //StreamWriter sw = new StreamWriter(cgmfilename_out, false);
            //foreach (Command cmd in commands)
            //{
            //    sw.WriteLine(cmd.toString());
            //}
            //sw.Close();
            #endregion
```

The text was also not not showing up in the converted SVG.  The text in your CGM are actually polygon sets.  To get the text to show up I had to change the logic used for the POLYGON SET invisible flag (Form1.cs : Line 3238) .

```
switch (cgmElement.polygonSetFlags[pt_idx])
                        {
                            case "invisible":

                                if (pt_idx == 0)
                                {
                                    polyset.Append(String.Format("M {0} {1} ", pt.X, pt.Y));
                                }
                                else
                                {
                                    polyset.Append(String.Format(" {0} {1} ", pt.X, pt.Y));
                                }

                                break;
                            case "visible":

```

Could you tell me how/what application you use to create your CGM files?

**Comment by alison84r** [comment]
Hi 
I tried to generate after the changes you asked in previous comment. But i am getting error. I have attached the snapshot for reference along with test case. 
![capture](https://cloud.githubusercontent.com/assets/12997350/20164334/0f9bacb2-a72a-11e6-81eb-3d9bc5ccb115.PNG)

**Comment by bjhamltn** [comment]
Before I was using my locale copy.  When I downloaded a copy of the project from Github I found a issue that my be causing your problem.

Near line Form1.cs: line 2821 there is a bug.

```
string[] cgmElemNames = cgm_struct.cgm_element_names.
    Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries);
```

"\r\n" may not be working.  Instead, split the string using \n.

I was able to decode your sample but the font is not accurate and the spacing of rotated text needs adjusting.

**Comment by alison84r** [comment]
Hi Bjhamltn,
I resolved the issue of texts. If you add following piece of attributes for
svg text it will be resolved.

path.Attributes.Append(cgm_svg.CreateAttribute("textLength"));

path.Attributes.Append(cgm_svg.CreateAttribute("font-size"));

path.Attributes.Append(cgm_svg.CreateAttribute("lengthAdjust"));

path.Attributes.Append(cgm_svg.CreateAttribute("xml:space"));
                    path.Attributes["textLength"].Value =
(cgmElement.delta_width).ToString();
                    path.Attributes["font-size"].Value =
(cgmElement.delta_height).ToString();
                    path.Attributes["lengthAdjust"].Value =
"spacingAndGlyphs";
                    path.Attributes["xml:space"].Value = "preserve";

Also there is one instance where the CGM to SVG not working. That is
multipage CGM is not able to export properly. Let us know what might be the
problem if you find.

Thanks & regards
Naga Reddy

**Comment by bjhamltn** [comment]
Thanks for the info on how to fix the text, I will have to add those changes.  

The CGM files that I work with are all single page files. I would appreciate it if you could share with me some multi page examples.  Also could you tell me how many files have you been able to convert.   

Thanks,

**Comment by alison84r** [comment]
Hi ,
Kindly find the multipage cgm example. Also I am attaching one simple cgm
file, for which I am not able to generate the output.
I am still in testing stage and till now I am able to generate around 100
cgm files. There are some geometry missing in some files. Figuring out
where it is been missing. Will keep you posted as and then I will make
changes.

Thanks & regards
Naga Reddy

**Comment by bjhamltn** [comment]
Naga,

Your attached were not received. Could you retry sending the files to my email?
I have made more improvements to the code that may fix some of your issues.   


Also, Thanks for the feedback.

**Comment by alison84r** [comment]
Kindly find the attachments.
Also i am trying to fix the svg in real units. I mean i want all
coordinates of the elements to be in mm.
We need to multiply all the values with some factor i think. Let me know
your views on this.
And thanks for the great code.

Thanks & regards
Naga Reddy
